# Generated by Django 4.2.6 on 2023-10-19 17:54

from django.db import migrations, models
import django.db.models.deletion
import storage.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrawlResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crawl_begin", models.DateTimeField(db_index=True)),
                ("crawl_end", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain_name", models.CharField(db_index=True, max_length=200)),
                (
                    "last_contacted",
                    models.DateTimeField(db_index=True, default=None, null=True),
                ),
                ("is_ignored", models.BooleanField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=300)),
                ("in_osm_data", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="CrawlResultError",
            fields=[
                (
                    "crawlresult_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="storage.crawlresult",
                    ),
                ),
                ("description_json", models.TextField()),
            ],
            bases=("storage.crawlresult",),
        ),
        migrations.CreateModel(
            name="OccurrenceInOsm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("osm_item_type", models.CharField(max_length=1)),
                ("osm_item_id", models.BigIntegerField()),
                ("osm_tag_key", models.CharField(max_length=100)),
                ("osm_tag_value", models.CharField(max_length=300)),
                (
                    "url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="storage.url"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisasterUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField()),
                (
                    "url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="storage.url"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="crawlresult",
            name="url",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="storage.url"
            ),
        ),
        migrations.CreateModel(
            name="CrawlResultSuccess",
            fields=[
                (
                    "crawlresult_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="storage.crawlresult",
                    ),
                ),
                ("status_code", models.PositiveSmallIntegerField()),
                ("headers_lz4", models.BinaryField(max_length=4096, null=True)),
                (
                    "content_lz4",
                    models.FileField(
                        null=True, upload_to=storage.models.user_directory_path
                    ),
                ),
                (
                    "next_url",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="storage.url",
                    ),
                ),
            ],
            bases=("storage.crawlresult",),
        ),
        migrations.CreateModel(
            name="CrawlableUrl",
            fields=[
                (
                    "url",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        primary_key=True,
                        serialize=False,
                        to="storage.url",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="storage.domain",
                    ),
                ),
            ],
        ),
    ]
