# Generated by Django 4.2.6 on 2023-10-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0002_remove_domain_is_ignored_remove_url_in_osm_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="url",
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
