# Generated by Django 4.2.6 on 2023-10-21 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0003_ensure_url_uniqueness"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="occurrenceinosm",
            options={
                "verbose_name": "occurrence in OSM",
                "verbose_name_plural": "occurrences in OSM",
            },
        ),
    ]
