# Generated by Django 4.2.6 on 2023-11-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0005_remove_crawl_result_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Import",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urlfile_name", models.CharField(max_length=200)),
                ("import_begin", models.DateTimeField()),
                ("import_end", models.DateTimeField()),
                ("additional_data", models.TextField()),
            ],
        ),
    ]
