# Generated by Django 4.2.6 on 2023-11-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0006_log_imports_as_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="domain_name",
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
