# Generated by Django 4.2.6 on 2023-11-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0007_add_constraint_unique_domain_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="url",
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
