# Generated by Django 4.2.6 on 2023-11-12 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0009_deduplicate_disasterurl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disasterurl",
            name="id",
        ),
        migrations.AlterField(
            model_name="disasterurl",
            name="url",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                primary_key=True,
                serialize=False,
                to="storage.url",
            ),
        ),
    ]
