# Generated by Django 4.2.6 on 2023-11-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0010_alter_disasterurl_one_to_one_on_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrenceinosm",
            name="osm_lat",
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name="occurrenceinosm",
            name="osm_long",
            field=models.FloatField(default=50),
        ),
    ]
