# Generated by Django 4.2.6 on 2023-10-22 17:33

import crawl.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("storage", "0005_remove_crawl_result_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crawl_begin", models.DateTimeField(db_index=True)),
                ("crawl_end", models.DateTimeField(db_index=True)),
                (
                    "url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="storage.url"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultError",
            fields=[
                (
                    "result_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="crawl.result",
                    ),
                ),
                ("description_json", models.TextField()),
            ],
            bases=("crawl.result",),
        ),
        migrations.CreateModel(
            name="ResultSuccess",
            fields=[
                (
                    "result_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="crawl.result",
                    ),
                ),
                ("status_code", models.PositiveSmallIntegerField()),
                ("headers_lz4", models.BinaryField(null=True)),
                ("headers_orig_size", models.PositiveIntegerField()),
                (
                    "content_lz4",
                    models.FileField(
                        null=True, upload_to=crawl.models.user_directory_path
                    ),
                ),
                ("content_truncated", models.PositiveIntegerField()),
                (
                    "next_request",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redir_set",
                        to="crawl.result",
                    ),
                ),
                (
                    "next_url",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="storage.url",
                    ),
                ),
            ],
            bases=("crawl.result",),
        ),
    ]
