# Generated by Django 4.2.6 on 2023-10-26 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crawl", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resultsuccess",
            old_name="content_lz4",
            new_name="content_file",
        ),
        migrations.RenameField(
            model_name="resultsuccess",
            old_name="content_truncated",
            new_name="content_orig_size",
        ),
        migrations.RenameField(
            model_name="resultsuccess",
            old_name="headers_lz4",
            new_name="headers_zlib",
        ),
        migrations.RemoveField(
            model_name="resulterror",
            name="result_ptr",
        ),
        migrations.RemoveField(
            model_name="resultsuccess",
            name="result_ptr",
        ),
        migrations.AddField(
            model_name="resulterror",
            name="result",
            field=models.OneToOneField(
                default=None,  # No rows should exist yet
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="crawl.result",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resultsuccess",
            name="result",
            field=models.OneToOneField(
                default=None,  # No rows should exist yet
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="crawl.result",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="result",
            name="crawl_end",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
