# Generated by Django 4.2.6 on 2023-10-27 00:48

import crawl.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawl", "0002_inheritance_zlib_and_optional_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultsuccess",
            name="content_file",
            field=models.FileField(
                db_index=True, null=True, upload_to=crawl.models.user_directory_path
            ),
        ),
    ]
