# Generated by Django 4.2.6 on 2023-10-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawl", "0003_index_resultsuccess_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultsuccess",
            name="content_orig_size",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="resultsuccess",
            name="headers_orig_size",
            field=models.IntegerField(),
        ),
    ]
