# Generated by Django 4.2.6 on 2023-10-29 00:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crawl", "0004_negative_numbers_for_inexact_bounds"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resultsuccess",
            old_name="headers_zlib",
            new_name="headers",
        ),
    ]
