# Generated by Django 4.2.6 on 2023-11-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawl", "0005_rename_headers_zlib_resultsuccess_headers"),
    ]

    operations = [
        migrations.AddField(
            model_name="resulterror",
            name="is_internal_error",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
